### ISSUE TITLE
Statistics expandable to show graphs

### ISSUE THREAD

**Issue by HaggitheSecond** [haefele/CTime2#55]

**Comment by haefele** [comment]
Other ideas:
- [x] **nope** Mark saturday and sundays somehow (can't find a way to make it look good)
- [x] If you click on a data-point switch to "My times" and show the selected day
- [x] Add a label at the data-points showing their value
- [x] Worktime and breaktime should be column diagrams?! (at a later point)
- [x] Workbegin and workend are still line diagrams, but we can combine both in one diagram
- [x] Show the weekday beneath the dates or as a separate axis above the diagram (not for now)
- [x] Format the values so they make more sense (16.30 instead of 16.5 for clock-out time)
